In [1]:
import json

In [124]:
# output a sample json file
with open('sample.json') as f:
    data = json.load(f)
data_out = [{(k):(float(v.replace(',', '')) if t=='real' and isinstance(v, str) and v else v) \
for k,v,t in zip(data['header'], row, data['types'])} for row in data['rows']]
with open('vega-lite.json', 'w') as outfile:
    json.dump(data_out, outfile)

In [86]:
# select possible qualified visualization questions
def filter_questions(part_file_name):
    with open('../WikiSQL/data/'+part_file_name+'.jsonl') as f:
        questions_list = f.readlines()

    filtered_questions_list = []
    for question in questions_list:
        question_json = json.loads(question)
        conds = question_json['sql']['conds']
        if len(conds) == 1 and conds[0][1] != 0:
            if question_json['sql']['agg'] >= 3:
                filtered_questions_list.append(question_json)
            
    return filtered_questions_list

In [100]:
def get_tables(part_file_name):
    with open('../WikiSQL/data/'+part_file_name+'.tables.jsonl') as f:
        tables_list = f.readlines()
        
    tables = {}
    for table in tables_list:
        table_json = json.loads(table)
        tables[table_json['id']] = table_json
    return tables

In [89]:
filtered_train_questions = filter_questions('train')
filtered_dev_questions = filter_questions('dev')
filtered_test_questions = filter_questions('test')

In [105]:
train_tables_dict = get_tables('train')
dev_tables_dict = get_tables('dev')
test_tables_dict = get_tables('test')

In [152]:
# show, what, how
def modify_questions(questions, tables_dict):
    new_questions = []
    for question in questions:
        table_id = question['table_id']
        table = tables_dict[table_id]
        header = table['header']
        sql = question['sql']
        sel = sql['sel']
        sel_col = header[sel]
        conds = sql['conds'][0][0]
        conds_col = header[conds]
        agg = sql['agg']
        if agg == 3:
            question['question1'] = 'What is the '+sel_col+' over different '+conds_col
            question['question2'] = 'How many '+sel_col+' over different '+conds_col
        elif agg == 4:
            question['question1'] = 'What is the sum of '+sel_col+' over different '+conds_col
            question['question2'] = 'How many '+sel_col+' over different '+conds_col
        else:
            question['question1'] = 'What is the average value of '+sel_col+' over different '+conds_col
            question['question2'] = 'How does the average '+sel_col+' distribute over different '+conds_col
        new_questions.append(question)
    return new_questions

In [158]:
new_train_questions = modify_questions(filtered_train_questions, train_tables_dict)
new_dev_questions = modify_questions(filtered_dev_questions, dev_tables_dict)
new_test_questions = modify_questions(filtered_test_questions, test_tables_dict)

file_names = ['new_train_questions', 'new_dev_questions', 'new_test_questions']
new_questions = [new_train_questions, new_dev_questions, new_test_questions]
for file_name, new_question in zip(file_names, new_questions):
    with open(file_name+'.txt', 'w') as outfile:
        for question in new_question:
            json.dump(question, outfile)
            outfile.write('\n')
            
# Then manually check, finish 1st 50 Saturday night
# Tell me the average Laps for different grid
# show, what, how

In [134]:
sample = json.loads(json_questions[0])
sample.keys()
a = filtered_train_questions[2]
a

{'phase': 1,
 'table_id': '1-12821159-14',
 'question': "How many listings are under money list rank wher 2nd' value is larger than 2.0?",
 'sql': {'sel': 9, 'conds': [[4, 1, 2.0]], 'agg': 3}}

In [135]:
filtered_train_questions[100]

{'phase': 2,
 'table_id': '2-14993344-2',
 'question': 'What is the average value for ERP W when frequency is more than 100.1?',
 'sql': {'sel': 3, 'conds': [[1, 1, 100.1]], 'agg': 5}}

In [109]:
train_tables_dict['1-10722506-6'].keys()

dict_keys(['header', 'page_title', 'types', 'id', 'section_title', 'caption', 'rows', 'name'])

In [117]:
train_tables_dict['1-10722506-6']['types']

['text', 'real', 'text', 'text', 'real', 'real', 'real', 'real', 'real']

In [116]:
[i[6] for i in train_tables_dict['1-10722506-6']['rows']]

[0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 0]

In [154]:
new_dev_questions

[{'phase': 2,
  'table_id': '2-1006029-1',
  'question': 'Name the average bronze for total less than 1',
  'sql': {'sel': 4, 'conds': [[5, 2, 1]], 'agg': 5},
  'question1': 'What is the average value of Bronze over different Total',
  'question2': 'How does the average Bronze distribute over different Total'},
 {'phase': 2,
  'table_id': '2-10637415-4',
  'question': 'What is the sum of losses for teams with less than 4 games played?',
  'sql': {'sel': 2, 'conds': [[1, 2, 4]], 'agg': 4},
  'question1': 'What is the sum of Lost over different Played',
  'question2': 'How many Lost over different Played'},
 {'phase': 2,
  'table_id': '2-10649583-2',
  'question': 'What is the average week number of all the matches where less than 22,604 people attended?',
  'sql': {'sel': 0, 'conds': [[4, 2, '22,604']], 'agg': 5},
  'question1': 'What is the average value of Week over different Attendance',
  'question2': 'How does the average Week distribute over different Attendance'},
 {'phase': 2,
  'table_id': '2-10650887-1',
  'question': 'How many weeks had an attendance larger than 84,816?',
  'sql': {'sel': 0, 'conds': [[4, 1, '84,816']], 'agg': 3},
  'question1': 'What is the Week over different Attendance',
  'question2': 'How many Week over different Attendance'},
 {'phase': 2,
  'table_id': '2-10650539-2',
  'question': 'What is the average attendance after week 16?',
  'sql': {'sel': 4, 'conds': [[0, 1, 16]], 'agg': 5},
  'question1': 'What is the average value of Attendance over different Week',
  'question2': 'How does the average Attendance distribute over different Week'},
 {'phase': 2,
  'table_id': '2-1514634-7',
  'question': 'How many top 10s when he had under 1 top 5s?',
  'sql': {'sel': 3, 'conds': [[2, 2, 1]], 'agg': 4},
  'question1': 'What is the sum of Top-10 over different Top-5',
  'question2': 'How many Top-10 over different Top-5'},
 {'phase': 2,
  'table_id': '2-15284070-1',
  'question': 'Which Position has a Played larger than 9?',
  'sql': {'sel': 0, 'conds': [[3, 1, 9]], 'agg': 4},
  'question1': 'What is the sum of Position over different Played',
  'question2': 'How many Position over different Played'},
 {'phase': 2,
  'table_id': '2-14660820-2',
  'question': 'What is the number for rank when gold is less than 0?',
  'sql': {'sel': 0, 'conds': [[2, 2, 0]], 'agg': 4},
  'question1': 'What is the sum of Rank over different Gold',
  'question2': 'How many Rank over different Gold'},
 {'phase': 2,
  'table_id': '2-14342367-5',
  'question': 'What is the average number of field goals for players with more than 60 points?',
  'sql': {'sel': 3, 'conds': [[4, 1, 60]], 'agg': 5},
  'question1': 'What is the average value of Field goals over different Points',
  'question2': 'How does the average Field goals distribute over different Points'},
 {'phase': 2,
  'table_id': '2-14641138-1',
  'question': "What's the total Rank that has a Gold that's smaller than 0?",
  'sql': {'sel': 0, 'conds': [[1, 2, 0]], 'agg': 4},
  'question1': 'What is the sum of Rank over different Gold',
  'question2': 'How many Rank over different Gold'},
 {'phase': 2,
  'table_id': '2-14641138-1',
  'question': "What is the total number of Participants that has Silver that's smaller than 0?",
  'sql': {'sel': 5, 'conds': [[2, 2, 0]], 'agg': 4},
  'question1': 'What is the sum of Participants over different Silver',
  'question2': 'How many Participants over different Silver'},
 {'phase': 2,
  'table_id': '2-14611644-3',
  'question': 'How many events have earnings less than 1,030,717?',
  'sql': {'sel': 4, 'conds': [[3, 2, '1,030,717']], 'agg': 3},
  'question1': 'What is the Events over different Earnings ( $ )',
  'question2': 'How many Events over different Earnings ( $ )'},
 {'phase': 2,
  'table_id': '2-15062102-1',
  'question': 'What is the total number of agriculatural panels of the composition with more than 3 National Universities of Ireland?',
  'sql': {'sel': 1, 'conds': [[5, 1, 3]], 'agg': 3},
  'question1': 'What is the Agricultural Panel over different National University of Ireland',
  'question2': 'How many Agricultural Panel over different National University of Ireland'},
 {'phase': 2,
  'table_id': '2-14177667-3',
  'question': "What is the total Gold's less than 0?",
  'sql': {'sel': 5, 'conds': [[2, 2, 0]], 'agg': 3},
  'question1': 'What is the Total over different Gold',
  'question2': 'How many Total over different Gold'},
 {'phase': 2,
  'table_id': '2-1519060-2',
  'question': 'How many wins did he have when he played under 2 events?',
  'sql': {'sel': 1, 'conds': [[4, 2, 2]], 'agg': 3},
  'question1': 'What is the Wins over different Events',
  'question2': 'How many Wins over different Events'},
 {'phase': 2,
  'table_id': '2-15423698-2',
  'question': 'What was the position with the total number less than 1?',
  'sql': {'sel': 0, 'conds': [[5, 2, 1]], 'agg': 3},
  'question1': 'What is the Position over different Lost',
  'question2': 'How many Position over different Lost'},
 {'phase': 2,
  'table_id': '2-1552908-21',
  'question': 'How many Against has Byes smaller than 2?',
  'sql': {'sel': 5, 'conds': [[2, 2, 2]], 'agg': 5},
  'question1': 'What is the average value of Against over different Byes',
  'question2': 'How does the average Against distribute over different Byes'},
 {'phase': 2,
  'table_id': '2-15419712-1',
  'question': 'What is the sum of Against when the lost is more than 7?',
  'sql': {'sel': 6, 'conds': [[5, 1, 7]], 'agg': 4},
  'question1': 'What is the sum of Against over different Lost',
  'question2': 'How many Against over different Lost'},
 {'phase': 2,
  'table_id': '2-15746812-4',
  'question': 'What is the total number of offensive rebounds for players with more than 124 3-point attempts?',
  'sql': {'sel': 6, 'conds': [[2, 1, 124]], 'agg': 3},
  'question1': 'What is the Off Reb over different 3FGA',
  'question2': 'How many Off Reb over different 3FGA'},
 {'phase': 2,
  'table_id': '2-15553293-2',
  'question': 'What is the total number of Silver with a Total that is smaller than 1?',
  'sql': {'sel': 3, 'conds': [[5, 2, 1]], 'agg': 3},
  'question1': 'What is the Silver over different Total',
  'question2': 'How many Silver over different Total'},
 {'phase': 2,
  'table_id': '2-160994-2',
  'question': 'What is the sum of Year 2007(s), when the Year 2005 is greater than 29,377?',
  'sql': {'sel': 1, 'conds': [[3, 1, '29,377']], 'agg': 4},
  'question1': 'What is the sum of Year 2007 over different Year 2005',
  'question2': 'How many Year 2007 over different Year 2005'},
 {'phase': 2,
  'table_id': '2-15405394-2',
  'question': 'What is the sum of drawn that has a played more than 12?',
  'sql': {'sel': 4, 'conds': [[3, 1, 12]], 'agg': 3},
  'question1': 'What is the Drawn over different Played',
  'question2': 'How many Drawn over different Played'},
 {'phase': 2,
  'table_id': '2-1543742-2',
  'question': 'What is the event average for a top-25 smaller than 0?',
  'sql': {'sel': 5, 'conds': [[4, 2, 0]], 'agg': 5},
  'question1': 'What is the average value of Events over different Top-25',
  'question2': 'How does the average Events distribute over different Top-25'},
 {'phase': 2,
  'table_id': '2-15826239-2',
  'question': 'What is the rank with 0 bronze?',
  'sql': {'sel': 0, 'conds': [[4, 2, 0]], 'agg': 5},
  'question1': 'What is the average value of Rank over different Bronze',
  'question2': 'How does the average Rank distribute over different Bronze'},
 {'phase': 2,
  'table_id': '2-15826239-2',
  'question': 'What is the total where the gold is larger than 2?',
  'sql': {'sel': 5, 'conds': [[2, 1, 2]], 'agg': 3},
  'question1': 'What is the Total over different Gold',
  'question2': 'How many Total over different Gold'},
 {'phase': 2,
  'table_id': '2-15400315-1',
  'question': 'What is the sum of Bronze when the total is more than 27?',
  'sql': {'sel': 4, 'conds': [[5, 1, 27]], 'agg': 4},
  'question1': 'What is the sum of Bronze over different Total',
  'question2': 'How many Bronze over different Total'},
 {'phase': 2,
  'table_id': '2-16183862-1',
  'question': 'What is the Year Commissioned of the power stationo with a Gross head of less than 18?',
  'sql': {'sel': 1, 'conds': [[2, 2, 18]], 'agg': 5},
  'question1': 'What is the average value of Year commissioned over different Gross head (metres)',
  'question2': 'How does the average Year commissioned distribute over different Gross head (metres)'},
 {'phase': 2,
  'table_id': '2-1590321-30',
  'question': 'What average goals have matches less than 228?',
  'sql': {'sel': 4, 'conds': [[3, 2, 228]], 'agg': 5},
  'question1': 'What is the average value of Goals over different Matches',
  'question2': 'How does the average Goals distribute over different Matches'},
 {'phase': 2,
  'table_id': '2-15368442-1',
  'question': 'What was the average Position for which the amount Drawn was less than 0?',
  'sql': {'sel': 0, 'conds': [[4, 2, 0]], 'agg': 5},
  'question1': 'What is the average value of Position over different Drawn',
  'question2': 'How does the average Position distribute over different Drawn'},
 {'phase': 2,
  'table_id': '2-17323912-2',
  'question': 'What is the total number of Points- when the Sets- is larger than 51?',
  'sql': {'sel': 4, 'conds': [[2, 1, 51]], 'agg': 3},
  'question1': 'What is the Points– over different Sets–',
  'question2': 'How many Points– over different Sets–'},
 {'phase': 2,
  'table_id': '2-16494005-1',
  'question': 'what is the sum of appearance when goals is more than 0?',
  'sql': {'sel': 1, 'conds': [[3, 1, 0]], 'agg': 4},
  'question1': 'What is the sum of Appearance over different Goals',
  'question2': 'How many Appearance over different Goals'},
 {'phase': 2,
  'table_id': '2-171368-2',
  'question': 'What is the population density of the area with a population larger than 92,719?',
  'sql': {'sel': 3, 'conds': [[1, 1, '92,719']], 'agg': 3},
  'question1': 'What is the Pop. Dens. over different Population',
  'question2': 'How many Pop. Dens. over different Population'},
 {'phase': 2,
  'table_id': '2-1662630-5',
  'question': 'what is the average top-5 when the cuts made is more than 34?',
  'sql': {'sel': 2, 'conds': [[6, 1, 34]], 'agg': 5},
  'question1': 'What is the average value of Top-5 over different Cuts made',
  'question2': 'How does the average Top-5 distribute over different Cuts made'},
 {'phase': 2,
  'table_id': '2-17412873-11',
  'question': 'What is the total championships that the league cup is less than 0?',
  'sql': {'sel': 1, 'conds': [[3, 2, 0]], 'agg': 4},
  'question1': 'What is the sum of Championship over different League Cup',
  'question2': 'How many Championship over different League Cup'},
 {'phase': 2,
  'table_id': '2-1720632-2',
  'question': 'What is the total code number for places with a population greater than 87,585?',
  'sql': {'sel': 1, 'conds': [[3, 1, '87,585']], 'agg': 3},
  'question1': 'What is the Code over different Population',
  'question2': 'How many Code over different Population'},
 {'phase': 2,
  'table_id': '2-16340209-1',
  'question': 'How many total golds do teams have when the total medals is less than 1?',
  'sql': {'sel': 2, 'conds': [[5, 2, 1]], 'agg': 4},
  'question1': 'What is the sum of Gold over different Total',
  'question2': 'How many Gold over different Total'},
 {'phase': 2,
  'table_id': '2-1637041-2',
  'question': 'How many wins for average start less than 25?',
  'sql': {'sel': 2, 'conds': [[4, 2, 25]], 'agg': 3},
  'question1': 'What is the Wins over different Avg. Start',
  'question2': 'How many Wins over different Avg. Start'},
 {'phase': 2,
  'table_id': '2-1637041-2',
  'question': 'How many starts for an average finish greater than 43?',
  'sql': {'sel': 1, 'conds': [[5, 1, 43]], 'agg': 4},
  'question1': 'What is the sum of Starts over different Avg. Finish',
  'question2': 'How many Starts over different Avg. Finish'},
 {'phase': 2,
  'table_id': '2-1646586-3',
  'question': 'Which Large end has a Taper/ft smaller than 0.6000000000000001?',
  'sql': {'sel': 1, 'conds': [[4, 2, 0.6000000000000001]], 'agg': 3},
  'question1': 'What is the Large end over different Taper/ ft',
  'question2': 'How many Large end over different Taper/ ft'},
 {'phase': 2,
  'table_id': '2-1646586-3',
  'question': 'Which Angle from center/° has a Taper/ft smaller than 0.6000000000000001?',
  'sql': {'sel': 6, 'conds': [[4, 2, 0.6000000000000001]], 'agg': 3},
  'question1': 'What is the Angle from center/° over different Taper/ ft',
  'question2': 'How many Angle from center/° over different Taper/ ft'},
 {'phase': 2,
  'table_id': '2-17610752-1',
  'question': 'Can you tell me the sum of FA Cup Goals that has the League Cup Goals larger than 0?',
  'sql': {'sel': 6, 'conds': [[8, 1, 0]], 'agg': 4},
  'question1': 'What is the sum of FA Cup Goals over different League Cup Goals',
  'question2': 'How many FA Cup Goals over different League Cup Goals'},
 {'phase': 2,
  'table_id': '2-17543955-4',
  'question': 'What is the sum for the match with a draw less than 0?',
  'sql': {'sel': 1, 'conds': [[3, 2, 0]], 'agg': 4},
  'question1': 'What is the sum of Match over different Draw',
  'question2': 'How many Match over different Draw'},
 {'phase': 2,
  'table_id': '2-17525117-2',
  'question': 'What is the number of losses when the ties are lesser than 0?',
  'sql': {'sel': 4, 'conds': [[5, 2, 0]], 'agg': 3},
  'question1': 'What is the Losses over different Ties',
  'question2': 'How many Losses over different Ties'},
 {'phase': 2,
  'table_id': '2-16640814-6',
  'question': 'What is the sum of total values for Rd 7 less than 8?',
  'sql': {'sel': 5, 'conds': [[3, 2, 8]], 'agg': 4},
  'question1': 'What is the sum of Total over different Rd 7',
  'question2': 'How many Total over different Rd 7'},
 {'phase': 2,
  'table_id': '2-16773359-1',
  'question': 'What is the total number for a place with points smaller than 12?',
  'sql': {'sel': 0, 'conds': [[7, 2, 12]], 'agg': 3},
  'question1': 'What is the Place over different Points',
  'question2': 'How many Place over different Points'},
 {'phase': 2,
  'table_id': '2-17309500-1',
  'question': 'How many blocks are there when the rebounds are fewer than 5.2?',
  'sql': {'sel': 4, 'conds': [[2, 2, 5.2]], 'agg': 3},
  'question1': 'What is the Blocks over different Rebounds',
  'question2': 'How many Blocks over different Rebounds'},
 {'phase': 2,
  'table_id': '2-11636955-11',
  'question': 'How many rounds exist for picks under 5?',
  'sql': {'sel': 0, 'conds': [[1, 2, 5]], 'agg': 3},
  'question1': 'What is the Rd # over different Pick #',
  'question2': 'How many Rd # over different Pick #'},
 {'phase': 2,
  'table_id': '2-11437463-1',
  'question': 'What is the average Draw when the Place is larger than 5?',
  'sql': {'sel': 0, 'conds': [[3, 1, 5]], 'agg': 5},
  'question1': 'What is the average value of Draw over different Place',
  'question2': 'How does the average Draw distribute over different Place'},
 {'phase': 2,
  'table_id': '2-11859949-3',
  'question': 'What is the average when the rank by average is more than 12?',
  'sql': {'sel': 5, 'conds': [[0, 1, 12]], 'agg': 4},
  'question1': 'What is the sum of Average over different Rank by average',
  'question2': 'How many Average over different Rank by average'},
 {'phase': 2,
  'table_id': '2-11753080-2',
  'question': 'What is the total ratings on share less than 4?',
  'sql': {'sel': 3, 'conds': [[4, 2, 4]], 'agg': 3},
  'question1': 'What is the Rating over different Share',
  'question2': 'How many Rating over different Share'},
 {'phase': 2,
  'table_id': '2-11164956-2',
  'question': 'What is the sum of the points of all teams that had against scores less than 14?',
  'sql': {'sel': 1, 'conds': [[5, 2, 14]], 'agg': 4},
  'question1': 'What is the sum of Points over different Against',
  'question2': 'How many Points over different Against'},
 {'phase': 2,
  'table_id': '2-11356674-6',
  'question': 'What is the total number of bronze when the total is less than 1?',
  'sql': {'sel': 4, 'conds': [[5, 2, 1]], 'agg': 4},
  'question1': 'What is the sum of Bronze over different Total',
  'question2': 'How many Bronze over different Total'},
 {'phase': 2,
  'table_id': '2-11621943-4',
  'question': 'On average, how many wins have a rank lower than 1?',
  'sql': {'sel': 4, 'conds': [[0, 2, 1]], 'agg': 5},
  'question1': 'What is the average value of Wins over different Rank',
  'question2': 'How does the average Wins distribute over different Rank'},
 {'phase': 2,
  'table_id': '2-11866-4',
  'question': 'What is the total word count with a subframe count greater than 3?',
  'sql': {'sel': 3, 'conds': [[0, 1, 3]], 'agg': 4},
  'question1': 'What is the sum of Word # over different Subframe #',
  'question2': 'How many Word # over different Subframe #'},
 {'phase': 2,
  'table_id': '2-1122569-1',
  'question': 'What is the total grid with laps less than 2?',
  'sql': {'sel': 4, 'conds': [[2, 2, 2]], 'agg': 4},
  'question1': 'What is the sum of Grid over different Laps',
  'question2': 'How many Grid over different Laps'},
 {'phase': 2,
  'table_id': '2-11563671-1',
  'question': 'What is the number of bronze medals when there are fewer than 0 silver medals?',
  'sql': {'sel': 3, 'conds': [[2, 2, 0]], 'agg': 4},
  'question1': 'What is the sum of Bronze over different Silver',
  'question2': 'How many Bronze over different Silver'},
 {'phase': 2,
  'table_id': '2-10831471-35',
  'question': 'How many snatches were there with a total of 267.5?',
  'sql': {'sel': 2, 'conds': [[4, 2, 267.5]], 'agg': 3},
  'question1': 'What is the Snatch over different Total',
  'question2': 'How many Snatch over different Total'},
 {'phase': 2,
  'table_id': '2-11097691-3',
  'question': 'What is the total of Apparent magnitudes for an NGC number larger than 3293?',
  'sql': {'sel': 5, 'conds': [[0, 1, 3293]], 'agg': 4},
  'question1': 'What is the sum of Apparent magnitude over different NGC number',
  'question2': 'How many Apparent magnitude over different NGC number'},
 {'phase': 2,
  'table_id': '2-11385308-1',
  'question': 'What is the average grid for the competitiors who had laps smaller than 3?',
  'sql': {'sel': 4, 'conds': [[2, 2, 3]], 'agg': 5},
  'question1': 'What is the average value of Grid over different Laps',
  'question2': 'How does the average Grid distribute over different Laps'},
 {'phase': 2,
  'table_id': '2-17693482-2',
  'question': 'How many Goals against have Played more than 34?',
  'sql': {'sel': 8, 'conds': [[2, 1, 34]], 'agg': 3},
  'question1': 'What is the Goals against over different Played',
  'question2': 'How many Goals against over different Played'},
 {'phase': 2,
  'table_id': '2-1830541-1',
  'question': 'After 1996, what is the average position?',
  'sql': {'sel': 3, 'conds': [[0, 1, 1996]], 'agg': 5},
  'question1': 'What is the average value of Position over different Year',
  'question2': 'How does the average Position distribute over different Year'},
 {'phase': 2,
  'table_id': '2-17968300-6',
  'question': 'What is the total number of points for a total pld less than 38?',
  'sql': {'sel': 4, 'conds': [[5, 2, 38]], 'agg': 3},
  'question1': 'What is the Total Pts over different Total Pld',
  'question2': 'How many Total Pts over different Total Pld'},
 {'phase': 2,
  'table_id': '2-17986709-4',
  'question': 'How much Peak Position has Sales Total larger than 1,540,088?',
  'sql': {'sel': 2, 'conds': [[3, 1, '1,540,088']], 'agg': 3},
  'question1': 'What is the Peak Position over different Sales Total',
  'question2': 'How many Peak Position over different Sales Total'},
 {'phase': 2,
  'table_id': '2-17982197-8',
  'question': 'What is the average of wins when the byes are less than 0?',
  'sql': {'sel': 1, 'conds': [[2, 2, 0]], 'agg': 5},
  'question1': 'What is the average value of Wins over different Byes',
  'question2': 'How does the average Wins distribute over different Byes'},
 {'phase': 2,
  'table_id': '2-17982197-8',

In [ ]:
tab_id = '2-14685454-1'
train_tables_dict[tab_id]

In [181]:
new_train_questions[37]

{'phase': 2,
 'table_id': '2-14891113-4',
 'question': 'Year larger than 2001 has what average points?',
 'sql': {'sel': 4, 'conds': [[0, 1, 2001]], 'agg': 5},
 'question1': 'What is the average value of Points over different Year',
 'question2': 'How does the average Points distribute over different Year'}